### ISSUE TITLE
models not avaialable?

### ISSUE THREAD

**Issue by oatmealm** [amir-zeldes/HebPipe#24]
Hi,I'm seeing the following error when `hebpipe` attempts to download models. Also, destination does not seem to be available using a browser.

```
Running tasks:
====================
o Automatic sentence splitting (neural)
o Whitespace tokenization
o Morphological segmentation

! Model file heb.sm3 missing in ./models/
! Model file heb.xrm missing in ./models/
! Model file heb.flair missing in ./models/
! Model file heb.morph missing in ./models/
! Model file heb.sent missing in ./models/
! Model file heb.diaparser missing in ./models/
! Model file stanza/he_lemmatizer.pt missing in ./models/
! Model file stanza/he_htb.pretrain.pt missing in ./models/
! You are missing required software:
 - Model files in models/ are missing
Attempt to download missing files? [Y/N]
Y
o Downloading from http://corpling.uis.georgetown.edu/amir/download/heb_models_v2/heb.sm3
Traceback (most recent call last):
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/site-packages/hebpipe/__init__.py", line 2, in <module>
    run_hebpipe()
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/site-packages/hebpipe/heb_pipe.py", line 863, in run_hebpipe
    download_requirements(models_OK)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/site-packages/hebpipe/heb_pipe.py", line 589, in download_requirements
    urlretrieve(u, model_dir + base_name)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/uri/.conda/envs/hebpipe/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Elapsed time: 0:00:00.010
```

**Comment by amir-zeldes** [comment]
Thanks for reporting - unfortunately the server hosting the models was subject to a cyber attack and is currently offline. We are working intensely on getting it back up, and I will post another comment here as soon as the models are available again.

**Comment by amir-zeldes** [comment]
All links should now be working, feel free to re-open if there are connectivity issues in the future.
