### ISSUE TITLE
Exception when trying to use example.in

### ISSUE THREAD

**Issue by galbraun** [amir-zeldes/HebPipe#3]
executing `python heb_pipe.py -wtplmdec example_in.txt` throwing this exception:
```Traceback (most recent call last):
  File "heb_pipe.py", line 675, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 511, in nlp
    tagged = inject_col(morphed,tokenized,5)
  File "c:\code\HebPipe\lib\append_column.py", line 65, in inject_col
    to_inject = source_cols[col]
IndexError: list index out of range
```

Python 3.7.6
Pip list:
```Package            Version             Location
------------------ ------------------- --------------------------
atomicwrites       1.4.0
attrs              19.3.0
backcall           0.1.0
boto               2.49.0
boto3              1.13.13
botocore           1.16.13
bpemb              0.3.0
certifi            2020.4.5.1
chardet            3.0.4
click              7.1.2
cloudpickle        1.4.1
colorama           0.4.3
cycler             0.10.0
Cython             0.29.14
datateam-dfi-tools 0.1.0               c:\code\datateam_dfi_tools
decorator          4.4.2
depedit            2.2.0.1
Deprecated         1.2.10
docutils           0.15.2
filelock           3.0.12
flair              0.4.5
future             0.18.2
gensim             3.8.3
hyperopt           0.2.4
idna               2.9
importlib-metadata 1.6.0
ipython            7.13.0
ipython-genutils   0.2.0
jedi               0.17.0
jmespath           0.10.0
joblib             0.15.1
kiwisolver         1.2.0
langdetect         1.0.8
matplotlib         3.1.2
more-itertools     8.3.0
mpld3              0.3
networkx           2.4
numpy              1.18.4
olefile            0.46
packaging          20.4
pandas             1.0.3
parso              0.7.0
pickleshare        0.7.5
Pillow             7.1.2
pip                20.0.2
pluggy             0.13.1
prompt-toolkit     3.0.4
py                 1.8.1
pyasn1             0.4.8
Pygments           2.6.1
pyparsing          2.4.7
pytest             5.4.2
python-dateutil    2.8.1
pytz               2020.1
regex              2020.5.14
requests           2.23.0
rsa                3.4.2
s3transfer         0.3.3
sacremoses         0.0.43
scikit-learn       0.22.1
scipy              1.4.1
segtok             1.5.10
sentencepiece      0.1.90
setuptools         46.4.0.post20200518
six                1.14.0
smart-open         2.0.0
sqlitedict         1.6.0
tabulate           0.8.7
tokenizers         0.7.0
torch              1.5.0
torchvision        0.6.0
tqdm               4.46.0
traitlets          4.3.3
transformers       2.9.1
urllib3            1.24.3
wcwidth            0.1.9
wheel              0.34.2
wincertstore       0.2
wrapt              1.12.1
xgboost            1.1.0
xmltodict          0.12.0
xrenner            2.1.0.3
zipp               3.1.0
```

**Comment by amir-zeldes** [comment]
Thanks for reporting; can you try removing everything then cloning the dev branch and running `python setup.py install` and re-running? It should fetch fresh models as well (if not, please make sure models/ is empty when it runs the first time). Does that work?

**Comment by galbraun** [comment]
Thanks for the quick answer! 
i deleted everything and installed the dev branch as you suggested and i get:

```
Processing example_in.txt
c:\code\HebPipe\lib\whitespace_tokenize.py:117: FutureWarning: Possible nested set at position 2
  m = re.match(r'(['+PChar+'])(.)',subunit)
c:\code\HebPipe\lib\whitespace_tokenize.py:120: FutureWarning: Possible nested set at position 3
  subunit = re.sub('^(['+PChar+'])(.)',r'\2',subunit)
Traceback (most recent call last):
  File "heb_pipe.py", line 675, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 476, in nlp
    tokenized = rf_tok.rf_tokenize(data.strip().split("\n"))
  File "c:\code\HebPipe\lib\tokenize_rf.py", line 815, in rf_tokenize
    self.load(self.model)
  File "c:\code\HebPipe\lib\tokenize_rf.py", line 478, in load
    self.tokenizer, self.num_labels, self.cat_labels, self.encoder, self.preparation_pipeline, self.pos_lookup, self.freqs, self.conf_file_parser = joblib.load(model_path)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\joblib\numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\joblib\numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\joblib\numpy_pickle.py", line 329, in load_build
    Unpickler.load_build(self)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\pickle.py", line 1552, in load_build
    setstate(state)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\xgboost\core.py", line 1212, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\xgboost\core.py", line 190, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [19:17:34] C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:846: Check failed: header == serialisation_header_:

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.
```

Pay attention that I couldn't `python setup.py install` as is, I'm using python 3.7 and there is some conflict with using sklearn 0.19.0 (as required by HebPipe) and using xrenner which require 0.21.
So i installed scikit-learn==0.22.1 - maybe this is my issue?

**Comment by amir-zeldes** [comment]
Actually I removed the sklearn restriction, and it's working fine for me with 0.22.1. From the error message it's looking like xgboost has made some kind of breaking change - can you try `xgboost==0.81`? 

If that fixes it, I'll update requirements.txt for this version, and then when I get a chance I can try retraining the model under the latest xgboost (might break Python 2.x compatibility though..).

**Comment by galbraun** [comment]
Seem that it helped but got a different exception now 😞  :
```
Traceback (most recent call last):
  File "heb_pipe.py", line 675, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 476, in nlp
    tokenized = rf_tok.rf_tokenize(data.strip().split("\n"))
  File "c:\code\HebPipe\lib\tokenize_rf.py", line 815, in rf_tokenize
    self.load(self.model)
  File "c:\code\HebPipe\lib\tokenize_rf.py", line 478, in load
    self.tokenizer, self.num_labels, self.cat_labels, self.encoder, self.preparation_pipeline, self.pos_lookup, self.freqs, self.conf_file_parser = joblib.load(model_path)
ValueError: not enough values to unpack (expected 8, got 7)
```

also got this warnings if that might help 🤷 :
```
c:\code\HebPipe\lib\whitespace_tokenize.py:117: FutureWarning: Possible nested set at position 2
  m = re.match(r'(['+PChar+'])(.)',subunit)
c:\code\HebPipe\lib\whitespace_tokenize.py:120: FutureWarning: Possible nested set at position 3
  subunit = re.sub('^(['+PChar+'])(.)',r'\2',subunit)
C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.preprocessing.label module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.20.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
```

**Comment by amir-zeldes** [comment]
OK, so this is a little weird, but I can get it to run as follows: I just tested this on a clean install of Python 3.7 on Win 10 64 (which it looks like you're using?) and it was missing scipy and joblib in the requirements. I just added these to setup.py and requirements.txt and then as expected, the only problem was `xgboost==0.81`. The weird part is, setuptools claims it can't find xgboost on PyPI:

```
Couldn't find index page for 'xgboost' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for xgboost==0.81
error: Could not find suitable distribution for Requirement.parse('xgboost==0.81')
```

Oddly though, directly pip installing it worked fine, and now your input works:

```
$ py -3.7 heb_pipe.py -wtplmdec example_in.txt


Running tasks:
====================
o Automatic sentence splitting
o Whitespace tokenization
o Morphological segmentation
o POS tagging
o Lemmatization
o Morphological analysis
o Dependency parsing
o Entity recognition
o Coreference resolution

1       עיפרון  עיפרון  PROPN   PROPN   _       0       root    _       (2-object)

1       עיפרון  עיפרון  PROPN   PROPN   _       3       nsubj:cop       _       (2-object)
2       הוא     הוא     VERB    VERB    Gender=Masc|Number=Sing|Person=3|Polarity=Pos|VerbForm=Part|VerbType=Cop        3       cop     _       _
3       כלי     כלי     NOUN    NOUN    Definite=Cons|Gender=Masc|Number=Sing   0       root    _       (4-abstract
4       כתיבה   כתיבה   NOUN    NOUN    Gender=Fem|Number=Sing  3       compound:smixut _       (5-abstract
5       ידני    ידני    ADJ     ADJ     Gender=Masc|Number=Sing 4       amod    _       5-abstract)
6       לשם     לשם     ADP     ADP     _       7       case    _       _
7       כתיבה   כתיבה   NOUN    NOUN    Gender=Fem|Number=Sing  3       nmod    _       (6-abstract)
8-9     וציור   _       _       _       _       _       _       _       _
8       ו       ו       CCONJ   CCONJ   _       9       cc      _       _
9       ציור    ציור    NOUN    NOUN    Gender=Masc|Number=Sing 7       conj    _       (8-event)
...
```

My pip list on this clean Python 3.7 shows:

```
$ py -3.7 -m pip list
Package         Version
--------------- ---------
depedit         2.2.0.1
flair           0.4.5
hebpipe         1.0.0.0
hyperopt        0.2.4
joblib          0.15.1
numpy           1.19.0rc1
pandas          1.0.3
pip             19.2.3
python-dateutil 2.8.1
pytz            2020.1
rftokenizer     1.0.1
scikit-learn    0.22.1
scipy           1.4.1
setuptools      41.2.0
six             1.15.0
tqdm            4.46.0
transformers    2.9.1
urllib3         1.24.3
xgboost         0.81
xmltodict       0.12.0
xrenner         2.1.0.3
```

I'll try to get to the bottom of the xgboost issue (or just retrain the model), but does this procedure work on your end too?

**Comment by galbraun** [comment]
Actually I don't have any issue with XGBoost but when I create a new clean environment during the installation I get an error:
```
Searching for torch>=1.1.0
Reading https://pypi.org/simple/torch/
No local packages or working download links found for torch>=1.1.0
error: Could not find suitable distribution for Requirement.parse('torch>=1.1.0')
```

After installing PyTorch manually I executed:

downloaded the most recent models and get an exception :( :
```
Processing example_in.txt
c:\code\HebPipe\lib\whitespace_tokenize.py:117: FutureWarning: Possible nested set at position 2
  m = re.match(r'(['+PChar+'])(.)',subunit)
c:\code\HebPipe\lib\whitespace_tokenize.py:120: FutureWarning: Possible nested set at position 3
  subunit = re.sub('^(['+PChar+'])(.)',r'\2',subunit)
C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\scikit_learn-0.22.1-py3.7-win-amd64.egg\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.preprocessing.label module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\scikit_learn-0.22.1-py3.7-win-amd64.egg\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.20.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "heb_pipe.py", line 672, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 508, in nlp
    tagged = inject_col(morphed,tokenized,5)
  File "c:\code\HebPipe\lib\append_column.py", line 65, in inject_col
    to_inject = source_cols[col]
IndexError: list index out of range
Elapsed time: 0:02:00.943
```


```
Package            Version             Location
------------------ ------------------- --------------------------
atomicwrites       1.4.0
attrs              19.3.0
boto               2.49.0
boto3              1.13.15
botocore           1.16.15
bpemb              0.3.0
certifi            2020.4.5.1
chardet            3.0.4
click              7.1.2
cloudpickle        1.4.1
colorama           0.4.3
cycler             0.10.0
cython             0.29.14
datateam-dfi-tools 0.1.0               c:\code\datateam_dfi_tools
decorator          4.4.2
depedit            2.2.0.1
deprecated         1.2.10
docutils           0.15.2
filelock           3.0.12
flair              0.4.5
future             0.18.2
gensim             3.8.3
hebpipe            1.0.0.0
hyperopt           0.2.4
idna               2.9
importlib-metadata 1.6.0
jmespath           0.10.0
joblib             0.15.1
kiwisolver         1.2.0
langdetect         1.0.8
matplotlib         3.1.2
more-itertools     8.3.0
mpld3              0.3
networkx           2.4
numpy              1.18.4
packaging          20.4
pandas             1.0.3
pip                20.0.2
pluggy             0.13.1
py                 1.8.1
pyasn1             0.4.8
pyparsing          3.0.0a1
pytest             5.4.2
python-dateutil    2.8.1
pytz               2020.1
regex              2020.5.14
requests           2.23.0
rftokenizer        1.0.1
rsa                3.4.2
s3transfer         0.3.3
sacremoses         0.0.43
scikit-learn       0.22.1
scipy              1.4.1
segtok             1.5.10
sentencepiece      0.1.91
setuptools         46.4.0.post20200518
six                1.15.0
smart-open         2.0.0
sqlitedict         1.6.0
tabulate           0.8.7
tokenizers         0.7.0
torch              1.5.0
tqdm               4.46.0
transformers       2.9.1
urllib3            1.24.3
wcwidth            0.1.9
wheel              0.34.2
wincertstore       0.2
wrapt              1.12.1
xgboost            0.81
xmltodict          0.12.0
xrenner            2.1.0.3
zipp               3.1.0
```

Again, thanks a lot for your help 🙏

**Comment by amir-zeldes** [comment]
OK, that's encouraging because it's not crashing on imports anymore. But it's odd that I can make it work on a clean Python 3.7 but yours crashes... And actually torch shouldn't matter since the Hebrew model in xrenner doesn't use pytorch. 

The error sounds like morphological analysis didn't output the right format. Oh wait, that's actually not done in Python - as the README mentions (see External Dependencies), you need to have Java since we're using Marmot and MaltParser. Do you have a working java in your path? If so can you paste output for java --version on the command line?

**Comment by galbraun** [comment]
Yeah i have:
```
C:\Users\galb>java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode)
```

**Comment by amir-zeldes** [comment]
Hm OK, then maybe it's something to do with Pytorch after all. I think the simplest solution is to just include a static version of xrenner without the dependencies, since the Hebrew model doesn't need them ATM anyway. I'll also need to bump RFTokenizer to sklearn 0.23+joblib but that should be easy.

Try doing a clean reinstall of the state in dev after this newest commit. Does that work? If so I can push it to PyPI to make it easier to install.

**Comment by galbraun** [comment]
Now I get:
```
Traceback (most recent call last):
  File "heb_pipe.py", line 10, in <module>
    from lib.xrenner import Xrenner
ModuleNotFoundError: No module named 'lib.xrenner'
```
so there is still dependency in xrenner.

**Comment by amir-zeldes** [comment]
Oh, sorry about that, some files were missing from the commit. Can you try again now?

**Comment by galbraun** [comment]
seem like some kind of conflict between joblib and sklearn's joblib? :\ 
```
Processing example_in.txt
Traceback (most recent call last):
  File "heb_pipe.py", line 671, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 472, in nlp
    tokenized = rf_tok.rf_tokenize(data.strip().split("\n"))
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\rftokenizer-1.1.0-py3.7.egg\rftokenizer\tokenize_rf.py", line 864, in rf_tokenize
    self.load()
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\rftokenizer-1.1.0-py3.7.egg\rftokenizer\tokenize_rf.py", line 527, in load
    self.tokenizer, self.num_labels, self.cat_labels, self.multicol_dict, pos_lookup, self.freqs, self.conf_file_parser = joblib.load(model_path)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\joblib-0.15.1-py3.7.egg\joblib\numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\site-packages\joblib-0.15.1-py3.7.egg\joblib\numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\galb\AppData\Local\Continuum\miniconda3\envs\heb_pipe_37\lib\pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
Elapsed time: 0:00:06.498
========================================
```

**Comment by amir-zeldes** [comment]
Are you sure you re-downloaded the model (heb.sm3)? The newest rftokenizer shouldn't be using sklearn.joblib at all since it's deprecated

**Comment by galbraun** [comment]
Absolutely right! forgot to delete them this time... 
But still, get this exception 😞 
```
Running tasks:
====================
o Automatic sentence splitting
o Whitespace tokenization
o Morphological segmentation
o POS tagging
o Lemmatization
o Morphological analysis
o Dependency parsing
o Entity recognition
o Coreference resolution

Processing example_in.txt
Traceback (most recent call last):
  File "heb_pipe.py", line 671, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 507, in nlp
    tagged = inject_col(morphed,tokenized,5)
  File "c:\code\HebPipe\lib\append_column.py", line 65, in inject_col
    to_inject = source_cols[col]
IndexError: list index out of range
Elapsed time: 0:00:33.477
========================================
```

**Comment by amir-zeldes** [comment]
This is right after it calls marmot, so my suspicion is either:

1. Permissions error (marmot output is written to a temp file, so if it can't write that morphology column won't exist)
2. Java error (e.g. out of memory because java_options set too low)

To test 1, open a new shell and run as admin. To test 2, uncomment line 263 in heb_pipe.py and see if it prints some error coming from java.

**Comment by galbraun** [comment]
1. I get the same output. 
2. My 263 line isn't commented out:
![image](https://user-images.githubusercontent.com/9768714/82760375-ca068b00-9dfb-11ea-9084-e88a001b762a.png)

which line do you mean? we are talking about the `dev` branch right?

**Comment by amir-zeldes** [comment]
259 (must have been looking at master)

**Comment by galbraun** [comment]
seems that the stderr is empty
```
Running tasks:
====================
o Automatic sentence splitting
o Whitespace tokenization
o Morphological segmentation
o POS tagging
o Lemmatization
o Morphological analysis
o Dependency parsing
o Entity recognition
o Coreference resolution

Processing example_in.txt
b''
Traceback (most recent call last):
  File "heb_pipe.py", line 671, in <module>
    sent_tag=opts.sent, preloaded=(rf_tok,xrenner))
  File "heb_pipe.py", line 507, in nlp
    tagged = inject_col(morphed,tokenized,5)
  File "c:\code\HebPipe\lib\append_column.py", line 65, in inject_col
    to_inject = source_cols[col]
IndexError: list index out of range
Elapsed time: 0:00:38.253
========================================
```

**Comment by amir-zeldes** [comment]
That's surprising... Can you try printing the variable output instead?

**Comment by galbraun** [comment]
I extracted the command line:
```
java -Dfile.encoding=UTF-8 -Xmx2g -cp marmot.jar;trove.jar marmot.morph.cmd.Annotator -model-file heb.marmot -lemmatizer-file heb.lemming -test-file form-index=0,C:\\Users\\galb\\AppData\\Local\\Temp\\tmpmv_mtq24 -pred-file C:\\Users\\galb\\AppData\\Local\\Temp\\tmpfv4ze_w1
``
and indeed when i executing this manually in the CMD i get:
```
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```
So i need to change java the limit in java options? I'll google how to do it and update

**Comment by amir-zeldes** [comment]
Yes, looks like java is not allowed to allocate 2GB on your machine. You can change java options in your environment variables.

**Comment by galbraun** [comment]
Yeah unfortunately I had Java 32bit. uninstalled and installed 64bit. Now working :) Thank you so much for the help!

**Comment by amir-zeldes** [comment]
Glad it's working now - I'll add a note about Java to the readme, and I'll try to get this project on pypi for convenience. Thanks for reporting the issue!

**Comment by amir-zeldes** [comment]
HebPipe is now deployed on PyPI and runnable as a module:

```
> pip install hebpipe
> python -m hebpipe
```
